export type MessageRole = 'user' | 'bot';


export type UUID = `${string}-${string}-${string}-${string}-${string}`;
export interface IChatMessage {
    id: UUID;                 // UUID generated by crypto.randomUUID()
    role: MessageRole;        // 'user' or 'bot'
    content: string;          // The actual message text
    timestamp: string;        // ISO format date-time string
}

//add msg to chat
export interface IChatRequest {
    messages: IChatMessage[];  
    userId: string;
    sessionId: string;
    isNewSession: boolean;
}

// bot reply
export interface IChatResponse {
    reply: IChatMessage;       
  }

export interface IChatHistory {
    userId: string;
    sessionId: string;
    messages: IChatMessage[];
    title: string;
    createdAt: Date;
    updatedAt: Date;
}
  


